services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    image: localhost/minecraft-mcp-backend:latest
    container_name: backend
    restart: "no"
    ports:
      - "3000:3000"
    entrypoint: ["node"]
    command: ["index.js"]
    environment:
      - NODE_ENV='development'
      - MINECRAFT_HOST='localhost'
      - MINECRAFT_PORT='25565'
      - MCRCON_HOST='localhost'
      - MCRCON_PORT='25575'
      - MCRCON_PASS='minecraft'

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    image: localhost/minecraft-mcp-frontend:latest
    container_name: frontend
    restart: "no"
    ports:
      - "3005:3005"
    depends_on:
      - backend
    entrypoint: ["node"]
    command: ["index.js"]
    environment:
      - NODE_ENV='development'
      - MINECRAFT_HOST='localhost'
      - MINECRAFT_PORT='25565'
      - MCRCON_HOST='localhost'
      - MCRCON_PORT='25575'
      - MCRCON_PASS='minecraft'
