services:
  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    image: localhost/minecraft-mcp-server:latest
    container_name: server
    restart: "no"
    ports:
      - "8080:8080"
    entrypoint: ["node"]
    command: ["index.js"]
    environment:
      - NODE_ENV='development'
      - MINECRAFT_HOST='localhost'
      - MINECRAFT_PORT='25565'
      - MCRCON_HOST='localhost'
      - MCRCON_PORT='25575'
      - MCRCON_PASS='minecraft'

  client:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    image: localhost/minecraft-mcp-client:latest
    container_name: client
    restart: "no"
    ports:
      - "3000:3000"
    depends_on:
      - server
    entrypoint: ["node"]
    command: ["index.js"]
    environment:
      - NODE_ENV='development'
      - MINECRAFT_HOST='localhost'
      - MINECRAFT_PORT='25565'
      - MCRCON_HOST='localhost'
      - MCRCON_PORT='25575'
      - MCRCON_PASS='minecraft'
