version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["./scripts/run.sh"]
    environment:
      - NODE_ENV='development'
      - MINECRAFT_HOST='localhost'
      - MINECRAFT_PORT='25565'
      - MCRCON_HOST='localhost'
      - MCRCON_PORT='25575'
      - MCRCON_PASS='minecraft'

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    command: ["./scripts/run.sh", "--client"]
    environment:
      - NODE_ENV='development'
      - MINECRAFT_HOST='localhost'
      - MINECRAFT_PORT='25565'
      - MCRCON_HOST='localhost'
      - MCRCON_PORT='25575'
      - MCRCON_PASS='minecraft'
